Replace executables with link to demos readme
audrow/yatm pull request #365
Opened 2023-05-09 07:17 UTC by Yadunund

Direct users to the demos readme to verify if the executables are present. Else we need to regularly update/maintain the test case.

2023-05-15 16:40 UTC, clalancette requested changes
I'm totally onboard with the idea.  I've left a few things to fix inline.

2023-05-16 05:16 UTC, Yadunund commented on requirements/features-executable-from-links.yaml
> +          - stdin: launch_test test/launch_testing/exffamples/good_proc_launch_test.py
Nice catch [2560349](https://github.com/audrow/yatm/pull/365/commits/2560349684dfd2fdd0b007ea2768adafea3a0539)

2023-05-16 05:17 UTC, Yadunund commented on requirements/features-executable-from-links.yaml
> +        url: https://github.com/ros2/demos/blob/rolling/composition/README.md
It would be cool if yatm had some kind of text substitution option to place the distro name with a variable. I'll open a feature request

2023-05-16 12:55 UTC, clalancette commented on requirements/features-executable-from-links.yaml
> +        url: https://github.com/ros2/demos/blob/rolling/composition/README.md
Yeah, agreed.  For now I think pointing to `iron` and then having to do the substitution is fine.

2023-05-16 12:56 UTC, merged